export default {
    data: [],
    agentInfo: [],
    bilingInfo: [],
    deliverInfo: [],
    manufacturerList: [],
    bilingListInfo: [],
    businessCom: [],
    searchDrugInfo: [],
    addDrugInfoCode: 0,
    delDrugInfoCode:0,
    searchManufacInfo:[],
    searchBilingComInfo:[],
    searchBusinessComInfo:[],
    agentInfo:[],
    searchManufacInfo:{},
    searchBilingComInfo:{},
    searchBusinessComInfo:{},
    drugList: [],
}