export default {
    powerList:[],
    hasPowerList:[],
    clickPowerList:[],
    id:'',
    powerClassification:[],
    clickPowerListInfo:[],
    roleMemberList:[],
    roleId:'',
    member_error_code:-1,
    memberList:[],
    roleApply:[],
    roleCheckId:'',
    code:0,
    changeCode:0,
    updateCode:0,
}
